## 1. Import pandas

In [ ]:
import pandas as pd

## 2. Read each file into a DataFrame

In [ ]:
aapl = pd.read_csv('/content/MSSP6070/Weekly Assignments/Week05/Data/aapl.csv')
amzn = pd.read_csv('/content/MSSP6070/Weekly Assignments/Week05/Data/amzn.csv')
fb = pd.read_csv('/content/MSSP6070/Weekly Assignments/Week05/Data/fb.csv')
goog = pd.read_csv('/content/MSSP6070/Weekly Assignments/Week05/Data/goog.csv')
nflx = pd.read_csv('/content/MSSP6070/Weekly Assignments/Week05/Data/nflx.csv')

aapl.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

## 3. Add the ticker column

In [ ]:
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'
nflx['ticker'] = 'NFLX'

aapl.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

## 4. Append the five DataFrames

In [ ]:
faang = pd.concat([aapl, amzn, fb, goog, nflx], ignore_index=True)
faang.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

## 5. Save the combined data as `faanf.csv`

In [ ]:
faang.to_csv('/content/MSSP6070/Weekly Assignments/Week05/Data/faanf.csv', index=False)
print('Saved Data/faanf.csv')

Saved Data/faanf.csv

## 6. Convert data types and sort

In [ ]:
faang['date'] = pd.to_datetime(faang['date'])
faang['volume'] = faang['volume'].astype(int)
faang = faang.sort_values(['date', 'ticker']).reset_index(drop=True)
faang.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

In [ ]:
faang.head(10)

## 7. Find the seven rows with the highest volume

In [ ]:
top7_volume = faang.nlargest(7, 'volume')
top7_volume

           date      open      high       low     close     volume ticker
712  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
267  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
287  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
272  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
910  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
1225 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
1060 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

## 8. Use `melt()` with `date` and `ticker` as identifiers

In [ ]:
faang_melted = faang.melt(id_vars=['date', 'ticker'])
faang_melted.head(10)

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000
5 2018-01-03   AAPL     open   169.2521
6 2018-01-03   AMZN     open  1188.3000
7 2018-01-03     FB     open   181.8800
8 2018-01-03   GOOG     open  1064.3100
9 2018-01-03   NFLX     open   202.0500

## 9. Final checks

In [ ]:
print('Combined DataFrame shape:', faang.shape)
print('\nTicker counts:')
print(faang['ticker'].value_counts())
print('\nTop 7 volume rows:')
display(top7_volume)
print('\nMelted DataFrame shape:', faang_melted.shape)

Combined DataFrame shape: (1255, 7)

Ticker counts:
ticker
AAPL    251
AMZN    251
FB      251
GOOG    251
NFLX    251
Name: count, dtype: int64

Top 7 volume rows:

           date      open      high       low     close     volume ticker
712  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
267  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
287  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
272  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
910  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
1225 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
1060 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

Melted DataFrame shape: (6275, 4)