# MSSP6070 Participation Activity Week 5

## 1. Import pandas

In [2]:
import pandas as pd

In [4]:
!git clone https://github.com/Theresa-Gao-0529/MSSP607.git /content/MSSP607

Cloning into '/content/MSSP607'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 140 (delta 53), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (140/140), 112.60 KiB | 1.61 MiB/s, done.
Resolving deltas: 100% (53/53), done.

In [5]:
import os

os.chdir('/content/MSSP607/Assignments/Week05')
print(os.getcwd())

/content/MSSP607/Assignments/Week05

## 2. Read each file into a DataFrame

In [6]:
aapl = pd.read_csv('Data/aapl.csv')
amzn = pd.read_csv('Data/amzn.csv')
fb = pd.read_csv('Data/fb.csv')
goog = pd.read_csv('Data/goog.csv')
nflx = pd.read_csv('Data/nflx.csv')

aapl.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

## 3. Add the `ticker` column

In [7]:
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'
nflx['ticker'] = 'NFLX'

aapl.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

## 4. Append all five DataFrames into one DataFrame

In [8]:
faang = pd.concat([aapl, amzn, fb, goog, nflx], ignore_index=True)
faang.shape

(1255, 7)

## 5. Save the results as `faanf.csv`

In [9]:
faang.to_csv('Data/faanf.csv', index=False)
print('Saved Data/faanf.csv')

Saved Data/faanf.csv

## 6. Convert data types and sort

In [10]:
faang['date'] = pd.to_datetime(faang['date'])
faang['volume'] = faang['volume'].astype(int)
faang = faang.sort_values(['date', 'ticker']).reset_index(drop=True)
faang.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

## 7. Find the seven rows with the highest volume

In [11]:
top7_volume = faang.nlargest(7, 'volume')
top7_volume

           date      open      high       low     close     volume ticker
712  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
267  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
287  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
272  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
910  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
1225 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
1060 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

## 8. Use `melt()` with `date` and `ticker` as key identifiers

In [12]:
faang_melted = faang.melt(id_vars=['date', 'ticker'])
faang_melted.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000

## 9. Final checks

In [13]:
print('Combined shape:', faang.shape)
print('Tickers:', sorted(faang['ticker'].unique()))
print('\nTop 7 volume rows:')
display(top7_volume)
print('\nMelted shape:', faang_melted.shape)

Combined shape: (1255, 7)
Tickers: ['AAPL', 'AMZN', 'FB', 'GOOG', 'NFLX']

Top 7 volume rows:

           date      open      high       low     close     volume ticker
712  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
267  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
287  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
272  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
910  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
1225 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
1060 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

Melted shape: (6275, 4)